In [43]:
import numpy as np

In [44]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [45]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [46]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [47]:
m.shape

(2, 3)

In [74]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [49]:
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [50]:
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [51]:
o.resize(3,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [52]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [53]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [54]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [55]:
np.diag(y)
# y = [4, 5, 6]

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [56]:
np.array(list(y) * 3)
# the * sign repeats the entire array n times

array([4, 5, 6, 4, 5, 6, 4, 5, 6])

In [57]:
np.repeat(list(y), 3)
# repeat() goes through each element n times

array([4, 4, 4, 5, 5, 5, 6, 6, 6])

In [58]:
p = np.ones([2,3], float)
p

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [59]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [61]:
# VERTICAL stack
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [62]:
# HORIZONTAL stack
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [63]:
x + y

array([5, 7, 9])

In [64]:
x * y

array([ 4, 10, 18])

In [65]:
x ** 2

array([1, 4, 9])

In [66]:
x.dot(y)

32

In [67]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [68]:
z.shape

(2, 3)

In [69]:
#the Transpose method is .T
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [70]:
z.T.shape

(3, 2)

In [71]:
z.dtype

dtype('int32')

In [73]:
z = z.astype('f')
z.dtype

dtype('float32')

In [77]:
a = np.array([-4,-2,1,3,5])
a

array([-4, -2,  1,  3,  5])

In [82]:
print (a.sum())
print (a.max())
print (a.min())
print (a.mean())

3
5
-4
0.6


In [83]:
#Standard Deviation

a.std()


3.2619012860600183

In [84]:
a.argmax()

4

In [85]:
a.argmin()

0

# Indexing/Slicing

In [88]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [90]:
s[::2]

array([  0,   4,  16,  36,  64, 100, 144])

In [93]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [94]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [95]:
r[2,2]

14

In [99]:
r[3,3:6]
#4rd, 5th, and 6th elements (Up to but not 7th) of the third row

array([21, 22, 23])

In [101]:
r[:2, :-1]
#First two rows
#Up to but not including the last element

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [103]:
r[r>30]

array([31, 32, 33, 34, 35])

In [106]:
r[r>30] = 30
#Using an inequality as an index to select certain elements
#and assign a value (30) on them
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Copying Data

In [111]:
r2 = r[:3,:3]
#Splicing a matrix out of a matrix
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [112]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [114]:
#NOTE: when you assign a matrix to be a splice of another matrix,
#changing the value of the new matrix will change the values of
#the original one as well. As shown.
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [115]:
k = np.arange(36)
k.resize(6,6)

#We can use the .copy() method to bypass this
k_copy = k.copy()
k_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [120]:
#As demonstrated
k_copy[:] = 0
print (k_copy)
print (k)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


# Iterating Over Arrays

In [123]:
test = np.random.randint(0, 10, (4, 3))
#Random integers from 0 to 10, in a 4 by 3 matrix
#Note: ROW x COL
test

array([[1, 0, 8],
       [1, 6, 8],
       [5, 6, 1],
       [5, 2, 4]])

In [125]:
for row in test:
    print (row)

[1 0 8]
[1 6 8]
[5 6 1]
[5 2 4]


In [126]:
for i in range(len(test)):
    print (test[i])

[1 0 8]
[1 6 8]
[5 6 1]
[5 2 4]


In [131]:
for i, row in enumerate(test):
    print ('row {} is {}'.format(i,row))

row 0 is [1 0 8]
row 1 is [1 6 8]
row 2 is [5 6 1]
row 3 is [5 2 4]


In [132]:
test2 = test**2
test2

array([[ 1,  0, 64],
       [ 1, 36, 64],
       [25, 36,  1],
       [25,  4, 16]])

In [133]:
for i, j in zip(test, test2):
    print ('{} + {} = {}'.format(i,j,i + j))

[1 0 8] + [ 1  0 64] = [ 2  0 72]
[1 6 8] + [ 1 36 64] = [ 2 42 72]
[5 6 1] + [25 36  1] = [30 42  2]
[5 2 4] + [25  4 16] = [30  6 20]


In [135]:
a = np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [138]:
a = a.reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [139]:
a[::7]

array([[0, 1, 2, 3, 4, 5]])

In [140]:
a[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [141]:
a[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [142]:
a.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [143]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [146]:
a[[2,3,4],[2,3,4]]
#Understood to be [2,2], [3,3], [4,4]

array([14, 21, 28])

In [147]:
a[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [148]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [149]:
a[:][2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [152]:
a[:,2:4]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]])

In [153]:
a[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [154]:
a[::2,::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [158]:
a

array([ 0,  7, 14, 21, 28, 35])

In [162]:
a = np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [165]:
a.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [166]:
a.reshape(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [167]:
a.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [169]:
a.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])